language: cpp

sudo: enabled

dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - gfortran 
      - libboost-all-dev
      - python3
      - python3-numpy

compiler:
  - gcc

env:
  - HDF5_ROOT=${HOME}/hdf5 SAMRAI_ROOT_NO_BOOST=${HOME}/SAMRAI_NO_BOOST SAMRAI_ROOT_WITH_BOOST=${HOME}/SAMRAI_WITH_BOOST

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - export CC=mpicc
  - export CXX=mpicxx
  - export F77=mpif77
  - sh travis/install-hdf5.sh
  - sh travis/install-SAMRAI_with_Boost.sh
  - sh travis/install-SAMRAI.sh

install:
  - export HAMERS_ROOT=$PWD
  - mkdir build_with_boost
  - cd build_with_boost
  - export SAMRAI_ROOT=$SAMRAI_ROOT_WITH_BOOST; cmake .. -DHAMERS_USE_BOOST=ON
  - make
  - cd ..
  - cd src/apps/Euler
  - ln -sf ${HAMERS_ROOT}/problems/Euler/initial_conditions/ConvergenceSingleSpecies.cpp EulerInitialConditions.cpp 
  - ln -sf ${HAMERS_ROOT}/problems/Euler/error_statistics/ConvergenceSingleSpecies.cpp EulerErrorStatistics.cpp
  - cd ../../..
  - mkdir build_convergence_test_single_species
  - cd build_convergence_test_single_species
  - export SAMRAI_ROOT=$SAMRAI_ROOT_NO_BOOST; cmake .. -DHAMERS_USE_BOOST=OFF
  - make
  - cd ..
  - cd src/apps/Euler
  - ln -sf ${HAMERS_ROOT}/problems/Euler/initial_conditions/ConvergenceFiveEqnAllaire.cpp EulerInitialConditions.cpp 
  - ln -sf ${HAMERS_ROOT}/problems/Euler/error_statistics/ConvergenceFiveEqnAllaire.cpp EulerErrorStatistics.cpp
  - cd ../../..
  - mkdir build_convergence_test_five_eqn_allaire
  - cd build_convergence_test_five_eqn_allaire
  - export SAMRAI_ROOT=$SAMRAI_ROOT_NO_BOOST; cmake .. -DHAMERS_USE_BOOST=OFF
  - make
  - cd ..

script:
  - ./build_convergence_test_single_species/src/test/test_mixing_rules
  - cd tests/2D_convergence_test_single_species; python3 convergence_test.py
  - cd ../..
  - cd tests/3D_convergence_test_single_species; python3 convergence_test.py
  - cd ../..
  - cd tests/2D_convergence_test_five_eqn_allaire; python3 convergence_test.py
  - cd ../..
  - cd tests/3D_convergence_test_five_eqn_allaire; python3 convergence_test.py
  - cd ../..
