language: cpp

sudo: enabled

dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - gfortran 
      - libboost-all-dev
      - python3
      - python3-numpy

compiler:
  - gcc

stages:
  - install_HDF5
  - install_SAMRAI
  - install_HAMeRS
  - test

env:
  - HDF5_ROOT=${TRAVIS_BUILD_DIR}/hdf5 SAMRAI_ROOT_NO_BOOST=${TRAVIS_BUILD_DIR}/SAMRAI_NO_BOOST SAMRAI_ROOT_WITH_BOOST=${TRAVIS_BUILD_DIR}/SAMRAI_WITH_BOOST HAMERS_ROOT=${TRAVIS_BUILD_DIR}

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - export CC=mpicc
  - export CXX=mpicxx
  - export F77=mpif77

jobs:
  include:
    - stage: install_HDF5
      script: sh travis/install-hdf5.sh
    - stage: install_SAMRAI
      script: sh travis/install-SAMRAI_with_Boost.sh
    -
      script: sh travis/install-SAMRAI.sh
    - stage: install_HAMeRS
      script: sh travis/install-HAMeRS_with_Boost.sh
    -
      script: sh travis/install-HAMeRS_convergence_test_single_species.sh
    -
      script: sh travis/install-HAMeRS_convergence_test_five_eqn_allaire.sh
    - stage: test
      script: ./build_convergence_test_single_species/src/test/test_mixing_rules
    -
      script: cd tests/2D_convergence_test_single_species; python3 convergence_test.py
    -
      script: cd tests/3D_convergence_test_single_species; python3 convergence_test.py
    -
      script: cd tests/2D_convergence_test_five_eqn_allaire; python3 convergence_test.py
    -
      script: cd tests/3D_convergence_test_five_eqn_allaire; python3 convergence_test.py
