language:
  - cpp
  - python

python:
  - "3.9"

sudo: enabled

dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - gfortran 
      - libboost-all-dev

compiler:
  - gcc

env:
  - HDF5_ROOT=${HOME}/hdf5 SAMRAI_ROOT_NO_BOOST=${HOME}/SAMRAI_NO_BOOST SAMRAI_ROOT_WITH_BOOST=${HOME}/SAMRAI_WITH_BOOST NUMPY_VERSION=1.14.0

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - export CC=mpicc
  - export CXX=mpicxx
  - export F77=mpif77
  - sh travis/install-hdf5.sh
  - sh travis/install-SAMRAI_with_Boost.sh
  - sh travis/install-SAMRAI.sh

install:
  - pip3 install numpy

script:
  - cd tests/2D_convergence_test_single_species/; python3 convergence_test.py
