language: cpp

sudo: enabled

dist: trusty

os:
  - linux

addons:
  apt:
    packages:
      - gfortran 
      - libboost-all-dev
      - python3
      - python3-numpy

compiler:
  - gcc

env:
  - HDF5_ROOT=${HOME}/hdf5 SAMRAI_ROOT_NO_BOOST=${HOME}/SAMRAI_NO_BOOST SAMRAI_ROOT_WITH_BOOST=${HOME}/SAMRAI_WITH_BOOST

before_install:
  - export HAMERS_ROOT=$PWD
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - export CC=mpicc
  - export CXX=mpicxx
  - export F77=mpif77
  - sh travis/install-hdf5.sh

jobs:
  include:
    - stage: install_SAMRAI
      script:
        - sh travis/install-SAMRAI_with_Boost.sh
        - sh travis/install-SAMRAI.sh
    - stage: install_HAMeRS
      script:
        - sh travis/install-HAMeRS_with_Boost.sh
        - sh travis/install-HAMeRS_convergence_test_single_species.sh
        - sh travis/install-HAMeRS_convergence_test_five_eqn_allaire.sh
    - stage: test
      script:
        - ./build_convergence_test_single_species/src/test/test_mixing_rules
        - cd tests/2D_convergence_test_single_species; python3 convergence_test.py
        - cd tests/3D_convergence_test_single_species; python3 convergence_test.py
        - cd tests/2D_convergence_test_five_eqn_allaire; python3 convergence_test.py
        - cd tests/3D_convergence_test_five_eqn_allaire; python3 convergence_test.py
