version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build_HDF5

jobs:
  build_HDF5:
    # working_directory: ~/mern-starter
    docker:
      - image: cimg/node:17.2.0 # Primary execution image
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      # - image: mongo:3.4.4         # Service/dependency image
      #   auth:
      #     username: mydockerhub-user
      #     password: $DOCKERHUB_PASSWORD  # context / project UI env-var
    steps:
      - checkout
      - run:
          name: "Setup environment variable HDF5_ROOT"
          command: echo 'export HDF5_ROOT=${CIRCLE_WORKING_DIRECTORY}/hdf5' >> $BASH_ENV
      - run:
          name: "Echo hdf5 root"
          command: echo $HDF5_ROOT
      - run:
          name: install_HDF5
          command: sh circleci/install-hdf5.sh
