version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build_HDF5

jobs:
  build_HDF5:
    docker:
      - image: cimg/node:17.2.0 # Primary execution image
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: "Setup compilers"
          command: >-
            test -n $CC  && unset CC &&
            test -n $CXX && unset CXX &&
            export CC=mpicc &&
            export CXX=mpicxx &&
            export F77=mpif77
      - run:
          name: "Setup environment variable HDF5_ROOT"
          command: >-
            echo 'export HDF5_ROOT=${PWD}/hdf5' >> $BASH_ENV &&
            echo 'export SAMRAI_ROOT_NO_BOOST=${PWD}/SAMRAI_NO_BOOST' >> $BASH_ENV &&
            echo 'export SAMRAI_ROOT_WITH_BOOST=${TRAVIS_BUILD_DIR}/SAMRAI_WITH_BOOST' >> $BASH_ENV &&
            echo 'export HAMERS_ROOT=${TRAVIS_BUILD_DIR}' >> $BASH_ENV
      - run:
          name: install_HDF5
          command: sh circleci/install-hdf5.sh
